name: nlp-question-answering-system
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1h=h7b6447c_0
  - pip=20.2.3=py37_0
  - python=3.7.9=h7579374_0
  - readline=8.0=h7b6447c_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - altair==4.1.0
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - async-generator==1.10
    - attrs==20.2.0
    - backcall==0.2.0
    - base58==2.0.1
    - bleach==3.2.1
    - blinker==1.4
    - boto3==1.16.0
    - botocore==1.19.0
    - cachetools==4.1.1
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - enum-compat==0.0.3
    - filelock==3.0.12
    - future==0.18.2
    - gitdb==4.0.5
    - gitpython==3.1.9
    - idna==2.10
    - importlib-metadata==2.0.0
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - jmespath==0.10.0
    - joblib==0.17.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.0.8
    - nest-asyncio==1.4.1
    - notebook==6.1.4
    - numpy==1.19.2
    - packaging==20.4
    - pandas==1.1.3
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.0.0
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.8
    - protobuf==3.13.0
    - ptyprocess==0.6.0
    - pyarrow==2.0.0
    - pycparser==2.20
    - pydeck==0.5.0b1
    - pygments==2.7.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyzmq==19.0.2
    - regex==2020.10.11
    - requests==2.24.0
    - s3transfer==0.3.3
    - sacremoses==0.0.43
    - send2trash==1.5.0
    - sentencepiece==0.1.91
    - six==1.15.0
    - smmap==3.0.4
    - streamlit==0.69.2
    - terminado==0.9.1
    - testpath==0.4.4
    - tokenizers==0.8.1rc2
    - toml==0.10.1
    - toolz==0.11.1
    - torch==1.6.0
    - tornado==6.0.4
    - tqdm==4.50.2
    - traitlets==5.0.5
    - transformers==3.3.1
    - tzlocal==2.1
    - urllib3==1.25.10
    - validators==0.18.1
    - watchdog==0.10.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.3.1
prefix: /home/snexus/anaconda3/envs/nlp-question-answering-system

